name: Update Badges Index

on:
  push:
    paths:
      - 'badges/**'
      - 'generate_badges_json.py'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate Badges JSON
      run: python generate_badges_json.py

    - name: Commit and Push if changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        if [[ -n $(git status --porcelain badges.json) ]]; then
          git add badges.json
          git commit -m "Update badges.json [skip ci]"
          git push
        else
          echo "No changes to badges.json"
        fi
